version: '3.8'

services:
  nginx:
    image: ghcr.io/energizer91/hack-my-leave-nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  frontend:
    image: ghcr.io/energizer91/hack-my-leave-frontend:latest
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  backend:
    image: ghcr.io/energizer91/hack-my-leave-backend:latest
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/vacation-planner
      - PORT=3000
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local

networks:
  default:
    driver: bridge
