version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - app_network

  frontend:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app_network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3050:3050"
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    volumes:
      - ./proxy/logs:/var/log/nginx

networks:
  app_network:
    driver: bridge