version: '3.8'
services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mvp
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    working_dir: /app

volumes:
  mongo-data:
